export const mockRecipes = [
    {
      id: "1",
      userId: "system",
      title: "Classic Margherita Pizza",
      author: "Chef Mario",
      image: "/images/pizza.jpg",
      cookingTime: 30,
      servings: 4,
      rating: 4.8,
      ingredients: [
        "500g pizza dough",
        "200g mozzarella cheese",
        "3 ripe tomatoes",
        "Fresh basil leaves",
        "2 tbsp olive oil",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Preheat your oven to 475°F (245°C).",
        "Roll out the pizza dough on a floured surface to your desired thickness.",
        "Slice the tomatoes and mozzarella.",
        "Place the dough on a pizza stone or baking sheet.",
        "Arrange the tomatoes and mozzarella on top of the dough.",
        "Bake for 12-15 minutes until the crust is golden.",
        "Remove from oven, top with fresh basil leaves, drizzle with olive oil, and season with salt and pepper.",
      ],
      dietary: ["vegetarian"],
      notes: "For the best flavor, use fresh buffalo mozzarella and San Marzano tomatoes if available.",
      substitutions: [
        {
          original: "Mozzarella cheese",
          substitute: "Vegan mozzarella for a dairy-free option",
        },
        {
          original: "Fresh basil",
          substitute: "1 tsp dried basil (but fresh is much better!)",
        },
      ],
    },
    {
      id: "2",
      userId: "system",
      title: "Spaghetti",
      author: "Baker Ben",
      image: "/images/spaghetti.jpg",
      cookingTime: 30,
      servings: 3,
      rating: 4.6,
      ingredients: [
        "1 lb spaghetti (use gluten-free spaghetti for gluten-free option)",
        "2 tbsp olive oil",
        "4 cloves garlic, minced",
        "1 medium onion, finely chopped",
        "1 red bell pepper, sliced",
        "1 zucchini, sliced",
        "1 cup cherry tomatoes, halved",
        "1/2 cup tomato sauce or crushed tomatoes",
        "1 tsp dried oregano",
        "1 tsp dried basil",
        "1/2 tsp red pepper flakes (optional, for heat)",
        "Salt and pepper to taste",
        "Fresh basil or parsley for garnish",
        "Nutritional yeast or vegan parmesan for topping (optional)",
      ],
      instructions: [
        "Cook spaghetti according to package instructions. Drain and set aside.",
        "Heat olive oil in a large pan over medium heat. Add chopped onions and garlic. Sauté until softened, about 3-4 minutes.",
        "Add the red bell pepper and zucchini to the pan. Cook for another 5 minutes until they begin to soften.",
        "Stir in the cherry tomatoes and cook for 2 minutes until they start to break down.",
        "Add the tomato sauce (or crushed tomatoes), oregano, basil, red pepper flakes (optional), salt, and pepper. Stir to combine.",
        "Let the sauce simmer for 5-7 minutes, stirring occasionally, until it thickens.",
        "Add the cooked spaghetti to the sauce and toss to combine, ensuring the spaghetti is well-coated.",
        "Serve with fresh basil or parsley on top. Optionally, sprinkle with nutritional yeast or vegan parmesan for extra flavor.",
      ],
      dietary: ["vegan", "vegetarian"],
      notes: "This recipe is perfect for meal prep! Store in an airtight container in the fridge for up to 3 days. Add any vegetables of your choice for variety, such as mushrooms or spinach.",
    },
    {
      id: "3",
      userId: "system",
      title: "Gluten-Free Banana Bread",
      author: "Healthy Hannah",
      image: "/images/banana.jpg",
      cookingTime: 60,
      servings: 10,
      rating: 4.5,
      ingredients: [
        "3 ripe bananas, mashed",
        "2 eggs",
        "1/3 cup melted coconut oil",
        "1/3 cup maple syrup",
        "1 tsp vanilla extract",
        "2 cups almond flour",
        "1 tsp baking soda",
        "1/2 tsp cinnamon",
        "1/4 tsp salt",
        "1/2 cup chopped walnuts (optional)",
      ],
      instructions: [
        "Preheat oven to 350°F (175°C) and line a loaf pan with parchment paper.",
        "In a large bowl, mix mashed bananas, eggs, coconut oil, maple syrup, and vanilla.",
        "In another bowl, combine almond flour, baking soda, cinnamon, and salt.",
        "Fold the dry ingredients into the wet ingredients until combined.",
        "Stir in chopped walnuts if using.",
        "Pour batter into the prepared loaf pan and bake for 50-55 minutes, or until a toothpick inserted comes out clean.",
        "Let cool completely before slicing.",
      ],
      dietary: ["gluten-free"],
      substitutions: [
        {
          original: "Eggs",
          substitute: "2 flax eggs (2 tbsp ground flaxseed + 6 tbsp water) for vegan option",
        },
        {
          original: "Maple syrup",
          substitute: "Honey (though this would no longer be vegan)",
        },
      ],
    },
    {
      id: "4",
      userId: "system",
      title: "Chicken Curry",
      author: "Chef Malini",
      image: "/images/chickencurry.jpg",
      cookingTime: 25,
      servings: 2,
      rating: 4.9,
      ingredients: [
        "1 lb chicken pieces (with bone or boneless, as preferred)",
        "4 cloves garlic, minced",
        "1-inch piece ginger, minced",
        "1 large onion, sliced",
        "2 green chilies, sliced",
        "2 tbsp vegetable oil or coconut oil",
        "1 tbsp curry powder (Sri Lankan curry powder if available)",
        "1/2 tsp turmeric powder",
        "1 tsp chili powder (adjust to spice level)",
        "1/2 tsp black pepper powder",
        "1 stick cinnamon",
        "2 cardamom pods",
        "2 cloves",
        "1 cup thick coconut milk",
        "1 cup water or chicken stock",
        "Salt to taste",
        "1 sprig curry leaves (optional but authentic)",
        "1 small tomato, chopped",
        "Fresh coriander leaves for garnish (optional)"
      ],
      instructions: [
        "Heat oil in a large pot over medium heat.",
        "Add sliced onions, garlic, ginger, green chilies, and curry leaves. Sauté until onions are soft and golden.",
        "Add curry powder, turmeric, chili powder, and black pepper. Stir for 30 seconds to release aromas.",
        "Add chicken pieces and mix well to coat with spices. Cook for about 5 minutes until chicken is lightly browned.",
        "Add chopped tomato, cinnamon stick, cardamom pods, and cloves. Stir and cook for another 2 minutes.",
        "Pour in coconut milk and water (or chicken stock). Season with salt.",
        "Bring to a boil, then reduce heat to low. Cover and simmer for 20–25 minutes until chicken is fully cooked and the curry is thickened.",
        "Taste and adjust seasoning if needed. Garnish with fresh coriander leaves if desired.",
        "Serve hot with steamed rice or roti."
      ],
      notes: "Adjust the number of chili peppers based on your spice preference.",
    },
    {
      id: "5",
      userId: "system",
      title: "Sri Lankan Coconut Sambol (Pol Sambol)",
      author: "Chef Nuwan",
      image: "/images/sambol.jpg",
      cookingTime: 15,
      servings: 4,
      rating: 4.7,
      ingredients: [
        "1 cup freshly grated coconut (or unsweetened desiccated coconut, soaked in warm water)",
        "1 small red onion, finely chopped",
        "2–3 dried red chilies (or 1 tsp red chili powder)",
        "1 green chili, sliced",
        "1 tsp Maldive fish flakes (optional)",
        "Juice of 1 lime",
        "Salt to taste",
      ],
      instructions: [
        "In a mortar and pestle (or food processor), grind the dried red chilies and salt into a coarse paste.",
        "Add chopped onion and green chili. Pound or pulse lightly to mix.",
        "Add grated coconut and Maldive fish (if using). Mix thoroughly.",
        "Squeeze in lime juice and adjust salt to taste.",
        "Serve fresh with rice, string hoppers, or coconut roti."
      ],
      dietary: ["vegetarian", "vegan", "gluten-free"],
      notes: "Adjust the number of chili based on your spice preference",
    },
    {
      id: "6",
      userId: "system",
      title: "Sri Lankan Pittu",
      author: "Chef Dilani Jayasuriya",
      image: "/images/pittu.jpg",
      cookingTime: 35,
      servings: 4,
      rating: 4.8,
      ingredients: [
        "2 cups rice flour (preferably fine flour)",
        "1 cup fresh grated coconut (or desiccated coconut, soaked in warm water)",
        "1/2 tsp salt (adjust to taste)",
        "1/2 cup warm water (add gradually)",
        "1 tbsp coconut oil (optional for richness)",
        "1-2 pandan leaves (optional for aroma)",
      ],
      instructions: [
        "Mix rice flour and salt in a large bowl.",
        "Gradually add warm water, mixing continuously until the flour becomes crumbly and resembles coarse breadcrumbs.",
        "Add the grated coconut to the flour mixture and mix well.",
        "Take a pittu mold (or bamboo tube) and lightly grease it with coconut oil.",
        "Layer the mixture in the pittu mold: start with a spoonful of the rice flour mixture, then add a layer of coconut, and repeat, finishing with coconut on top.",
        "If using pandan leaves, place them at the bottom of the mold for added fragrance.",
        "Steam the pittu for about 15-20 minutes or until cooked through (you can check by pressing gently, it should hold together).",
        "Serve hot with coconut milk and your favorite curry."
      ],
      dietary: ["vegetarian"],
      substitutions: [
        {
          original: "Rice flour",
          substitute: "Sorghum flour or millet flour (if rice flour is unavailable)",
        },
        {
          original: "Fresh grated coconut",
          substitute: "Desiccated coconut (soaked in warm water) or shredded coconut flakes",
        },
        {
          original: "Coconut oil",
          substitute: "Olive oil or any neutral vegetable oil",
        },
      ],
    },
  ]